In [1]:
import gymnasium as gym
import time
import numpy as np
num_states = 16   
num_actions = 4   

Q_table = np.zeros((num_states, num_actions))

print(Q_table)

env=gym.make("FrozenLake-v1",render_mode="human",is_slippery=True)
obs=env.reset()
print(f"Espace d'actions: {env.action_space}")
print(f"Espace d'observation: {env.observation_space}")
for _ in range(100):
    action=env.action_space.sample()
    obs,reward,terminated,_,_=env.step(action)
    print(f"Action :{action},Observation:{obs},Reward:{reward}")
    if terminated:
        obs=env.reset()
env.close()


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Espace d'actions: Discrete(4)
Espace d'observation: Discrete(16)
Action :2,Observation:1,Reward:0.0
Action :3,Observation:1,Reward:0.0
Action :0,Observation:0,Reward:0.0
Action :3,Observation:0,Reward:0.0
Action :3,Observation:0,Reward:0.0
Action :3,Observation:0,Reward:0.0
Action :0,Observation:4,Reward:0.0
Action :0,Observation:0,Reward:0.0
Action :0,Observation:4,Reward:0.0
Action :3,Observation:4,Reward:0.0
Action :2,Observation:8,Reward:0.0
Action :2,Observation:12,Reward:0.0
Action :1,Observation:4,Reward:0.0
Action :0,Observation:0,Reward:0.0
Action :2,Observation:4,Reward:0.0
Action :1,Observation:4,Reward:0.0
Action :2,Observation:8,Reward:0.0
Action :1,Observation:9,Reward:0.0
Action :3,Observation:8,Reward:0.0
Action :1,Observation:9,Rewa

In [4]:
num_states = 16   
num_actions = 4   
#qst1
Q_table = np.zeros((num_states, num_actions))


In [5]:
#qst2
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
#qst3
for i in range(num_states):
    print(i)
    print(Q_table[i])

0
[0. 0. 0. 0.]
1
[0. 0. 0. 0.]
2
[0. 0. 0. 0.]
3
[0. 0. 0. 0.]
4
[0. 0. 0. 0.]
5
[0. 0. 0. 0.]
6
[0. 0. 0. 0.]
7
[0. 0. 0. 0.]
8
[0. 0. 0. 0.]
9
[0. 0. 0. 0.]
10
[0. 0. 0. 0.]
11
[0. 0. 0. 0.]
12
[0. 0. 0. 0.]
13
[0. 0. 0. 0.]
14
[0. 0. 0. 0.]
15
[0. 0. 0. 0.]


In [ ]:
#ex3
#qst1
alpha = 0.1
gamma = 0.99
epsilon = 1.0
epsilon_decay=0.995
num_episodes = 5000
max_steps = 100  
epsilon_min = 0.01  

In [36]:
env = gym.make("FrozenLake-v1", is_slippery=True)
num_states = env.observation_space.n
num_actions = env.action_space.n
Q_table = np.zeros((num_states, num_actions)) 

for episode in range(num_episodes):
    state, _ = env.reset()  
    state = state  
    done = False
    
    for step in range(max_steps):
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()  
        else:
            action = np.argmax(Q_table[state, :])  

        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated  

        best_next_action = np.max(Q_table[next_state, :])  
        Q_table[state, action] = Q_table[state, action] + alpha * (reward + gamma * best_next_action - Q_table[state, action])

        state = next_state

        if done:
            break  

    if epsilon > epsilon_min:
        epsilon *= epsilon_decay
    
    if (episode + 1) % 100 == 0:
        print(f"Épisode {episode + 1} :")
        print(Q_table)
        print("=" * 50)

env.close()

print("Q-table après apprentissage :")
print(Q_table)


Épisode 100 :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Épisode 200 :
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.1]
 [0.  0.  0.  0. ]]
Épisode 300 :
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0.1]
 [0.  0.  0.  0. ]]
Épisode 400 :
[[0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. 

In [ ]:
#ex4 dst1
import numpy as np
import gymnasium as gym

env = gym.make("FrozenLake-v1", is_slippery=True)
num_states = env.observation_space.n
num_actions = env.action_space.n
Q_table = np.zeros((num_states, num_actions))

alpha = 0.1
gamma = 0.99
num_episodes = 100
max_steps = 100

for episode in range(num_episodes):
    state, _ = env.reset()
    state = state
    done = False
    
    for step in range(max_steps):
        action = np.argmax(Q_table[state, :])
        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
        state = next_state
        
        if done:
            break
    
    print(f"Épisode {episode + 1} terminé.")

env.close()


Épisode 1 terminé.
Épisode 2 terminé.
Épisode 3 terminé.
Épisode 4 terminé.
Épisode 5 terminé.
Épisode 6 terminé.
Épisode 7 terminé.
Épisode 8 terminé.
Épisode 9 terminé.
Épisode 10 terminé.
Épisode 11 terminé.
Épisode 12 terminé.
Épisode 13 terminé.
Épisode 14 terminé.
Épisode 15 terminé.
Épisode 16 terminé.
Épisode 17 terminé.
Épisode 18 terminé.
Épisode 19 terminé.
Épisode 20 terminé.
Épisode 21 terminé.
Épisode 22 terminé.
Épisode 23 terminé.
Épisode 24 terminé.
Épisode 25 terminé.
Épisode 26 terminé.
Épisode 27 terminé.
Épisode 28 terminé.
Épisode 29 terminé.
Épisode 30 terminé.
Épisode 31 terminé.
Épisode 32 terminé.
Épisode 33 terminé.
Épisode 34 terminé.
Épisode 35 terminé.
Épisode 36 terminé.
Épisode 37 terminé.
Épisode 38 terminé.
Épisode 39 terminé.
Épisode 40 terminé.
Épisode 41 terminé.
Épisode 42 terminé.
Épisode 43 terminé.
Épisode 44 terminé.
Épisode 45 terminé.
Épisode 46 terminé.
Épisode 47 terminé.
Épisode 48 terminé.
Épisode 49 terminé.
Épisode 50 terminé.
Épisode 5

In [ ]:
#qst2   
import numpy as np
import gymnasium as gym

env = gym.make("FrozenLake-v1", is_slippery=True)
num_states = env.observation_space.n
num_actions = env.action_space.n
Q_table = np.zeros((num_states, num_actions))

alpha = 0.1
gamma = 0.99
num_episodes = 100
max_steps = 100

successful_episodes = 0 

for episode in range(num_episodes):
    state, _ = env.reset()
    done = False

    for step in range(max_steps):
        if np.random.rand() < epsilon:  
            action = np.random.choice(num_actions)
        else: 
            action = np.argmax(Q_table[state, :])

        next_state, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
        Q_table[state, action] = (1 - alpha) * Q_table[state, action] + alpha * (reward + gamma * np.max(Q_table[next_state, :]))
        
        state = next_state
        
        if done:
            if terminated and reward == 1:
                successful_episodes += 1
            break
    
    print(f"Épisode {episode + 1} terminé.")

success_rate = successful_episodes / num_episodes
print(f"Taux de réussite : {success_rate * 100}%")

env.close()


Épisode 1 terminé.
Épisode 2 terminé.
Épisode 3 terminé.
Épisode 4 terminé.
Épisode 5 terminé.
Épisode 6 terminé.
Épisode 7 terminé.
Épisode 8 terminé.
Épisode 9 terminé.
Épisode 10 terminé.
Épisode 11 terminé.
Épisode 12 terminé.
Épisode 13 terminé.
Épisode 14 terminé.
Épisode 15 terminé.
Épisode 16 terminé.
Épisode 17 terminé.
Épisode 18 terminé.
Épisode 19 terminé.
Épisode 20 terminé.
Épisode 21 terminé.
Épisode 22 terminé.
Épisode 23 terminé.
Épisode 24 terminé.
Épisode 25 terminé.
Épisode 26 terminé.
Épisode 27 terminé.
Épisode 28 terminé.
Épisode 29 terminé.
Épisode 30 terminé.
Épisode 31 terminé.
Épisode 32 terminé.
Épisode 33 terminé.
Épisode 34 terminé.
Épisode 35 terminé.
Épisode 36 terminé.
Épisode 37 terminé.
Épisode 38 terminé.
Épisode 39 terminé.
Épisode 40 terminé.
Épisode 41 terminé.
Épisode 42 terminé.
Épisode 43 terminé.
Épisode 44 terminé.
Épisode 45 terminé.
Épisode 46 terminé.
Épisode 47 terminé.
Épisode 48 terminé.
Épisode 49 terminé.
Épisode 50 terminé.
Épisode 5